global using SpendWise.Infrastructure.Repositories;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using SpendWise.Domain.Entities;
global using SpendWise.Infrastructure.Data;
global using SpendWise.Infrastructure.Identity;
global using SpendWise.API.Mapping;
global using SpendWise.API.Features.CategoryMaster.DTOs;
global using SpendWise.API.Features.CategoryMaster;
global using Microsoft.AspNetCore.Mvc;
global using System.ComponentModel.DataAnnotations;
global using SpendWise.API.Common;
global using AutoMapper;
global using SpendWise.API.Features.PaymentMethod.DTOs;
global using SpendWise.API.Features.PaymentMethod;
global using SpendWise.API.Features.Notification.DTOs;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using SpendWise.API.Features.Authentication.DTOs;
global using Microsoft.OpenApi.Models;
global using SpendWise.API.Features.Authentication;
global using SpendWise.API.Features.Notification;
global using System.Text;
global using Microsoft.AspNetCore.Authorization;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using SpendWise.API.Features.UserCategory.DTOs;
global using SpendWise.API.Features.Transaction.DTOs;
global using Microsoft.AspNetCore.Http;
global using SpendWise.API.Features.UserCategory;
global using SpendWise.Infrastructure.FileStorage;
global using SpendWise.API.Features.Transaction;
global using SpendWise.API.Common.DateRange;
global using SpendWise.API.Features.UserDashboard.DTOs;
global using SpendWise.API.Features.UserDashboard;
global using SpendWise.API.Features.UserReport.DTOs;
global using SpendWise.API.Common.Reporting;
global using SpendWise.API.Features.UserReport;
global using SpendWise.API.Features.AdminDashboard;
global using CategoryMasterEntity = SpendWise.Domain.Entities.CategoryMaster;
global using NotificationEntity = SpendWise.Domain.Entities.Notification;
global using UserCategoryEntity = SpendWise.Domain.Entities.UserCategory;
global using TransactionEntity = SpendWise.Domain.Entities.Transaction;
global using DateRangeModal = SpendWise.API.Common.DateRange.DateRange;
global using PaymentMethodEntity = SpendWise.Domain.Entities.PaymentMethod;
global using TransactionAttachmentEntity = SpendWise.Domain.Entities.TransactionAttachment;
global using SpendWise.API.Services;