name: SpendWise CI

on: 
  push: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore SpendWise.API/SpendWise.API.csproj

      - run: dotnet build SpendWise.API/SpendWise.API.csproj --no--restore

      
      
          
      
